config/routes.rb
Rails.application.routes.draw do
  devise_for :books
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => "homes#about", as:'about'
  resources :books, only:[:new, :create, :index, :edit, :update, :show, :destroy]
  resources :users, only:[:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable=
  has_one_attached :image
  belongs_to :user

    validates :title, presence: true
  validates :body, presence: true, length:{maximum: 200}

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/post_image.rb
class PostImage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

   validates :name, length: {minimum: 2, maximum: 20 }, uniqueness: true
   validates :introduction, length: {maximum: 50}


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename:'default-image.jpg', content_type:'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width, height]).processed
  end


  has_many :books, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
   user_path(current_user.id)
   end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :login_user_matching, only: [:edit, :update]


  def new
    @book=Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have created book successfully."
     redirect_to book_path(@book.id)
    else
     @books=Book.all
      @user= current_user
     render :index
    end
  end

  def index
    @book=Book.new
    @books=Book.all
    @user= current_user
  end

  def edit
    @book=Book.find(params[:id])

  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def show
    @newbook=Book.new
    @book=Book.find(params[:id])
    @user=@book.user
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end



  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

   def login_user_matching
    @book= Book.find(params[:id])
    user_id=@book.user_id
    login_user_id = current_user.id
    if(user_id != login_user_id)
     redirect_to books_path
    end
   end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action:login_user_matching, only:[:edit, :update]

  def index
    @users=User.all
    @user=current_user
    @book=Book.new
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def show
    @user=User.find(params[:id])
    @books=@user.books
    @book=Book.new
    

  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def login_user_matching
    user_id = params[:id].to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)

     redirect_to user_path(login_user_id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new_book.html.erb
<div class='col-md-3'>
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
     </tr>
     <tr>
       <th>introduction</th>
    <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<%= link_to  edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog"></i>
<% end %>

<h2>New book</h2>
  <%= form_with model: book do |f| %>
    <label>Title</label><br>
      <%= f.text_field :title %><br>
    <label>Opinion</label><br>
      <%= f.text_area :body %><br>
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  <% end %>

  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model:@book do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label><br>
        <%= f.text_field :title, autofocus: true,id: "book_title", class:"form-controll book_title" %><br>
      </div>
      <div class="form-group">
        <label for="opinion">Opinion</label><br>
        <%= f.text_area :body, autofocus: true, id: "opinion", class:"form-control opinion" %>
      </div>
      <%= f.submit "Update Book", class:"btn btn-success" %>
      <% end %>

      <p>
      <%= link_to "Show", book_path %> |
      <%= link_to "Back", books_path %>
      </p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
        <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
<div class="container">
  <div class="row">
    <%= render 'new_book', book: @book, user: @user %>

    <div class="new-book col-md-8 offset-md-1"　>
      <h2>Books</h2>
      <table class="table">
      <thead>
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
         <tr>
          <th>
            <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
            </th>
          <th>
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
            </th>
          <th><%= book.body%></th>
         </tr>
         <% end %>
      </tbody>

      </table>
      </div>
  </div>
</div>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'new_book', book: @newbook, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= image_tag @user.get_profile_image(100,100) %><br>
              <%= link_to @user.name, user_path(@user.id) %></td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, "data-confirm"=>"本当に消しますか？", class: "btn btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
        <h1 class="px-3 mx-auto">Welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          !
        </h1>
      </div>
    </div>
  </div>

app/views/homes/top.html.erb
<main>
  <div>
  <%= flash[:notice] %>
</div>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-9 col-xl-6">
        <h1>welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
        </h1>
        <p>In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>,
        </p>
        <p>you can share and exchange your opinions , inpressions . and emotions</p>
        <p>about various books!</p>

        <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <%= link_to "Log in", user_session_path, class:"btn btn-info btn-block mb-3 sign_in" %>
            </div>
            <div class="row">
              <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-block" %>
            </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_notification.html.erb
<div class="Notification">
 <% flash.each do |key, value| %>
 <%= content_tag :div, value, class: key %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navnar-expand-lg navbar-dark bg-dark">
      <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to '/users', class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i>
                Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to '/books', class: 'nav-link text-light' do %>
                <i class='fas fa-book-open'></i>
                Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>
                Log out
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>
                Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>
                Log in
              <% end %>
            </li>
            <% end %>
            </ul>
        </div>
      </div>
      </nav>
    </header>
    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
<%= form_with model: @user do |f| %>
  <div class="form-group">
    <label for="inputName">Name</label><br>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%>
  </div>
  <div class="form-group">
    <label for="inputImage">Image</label><br>
    <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %>
  </div>
  <div class="form-group">
    <label for="inputIntroduction">Introduction</label><br>
    <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction" %>
  </div>
  <%= f.submit "Update User", class:"btn btn-success" %>
<% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
   <%= render 'books/new_book', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <th><%= image_tag user.get_profile_image(100,100) %> </th>
            <th><%= user.name %></th>
            <th><%= link_to 'Show', user_path(user.id) %> </th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
  <div class="row">
   <%= render 'books/new_book', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
         <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= image_tag @user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>